### PR TITLE
Add Unexpected Maker TinyS2

### PR DESCRIPTION
**Pull request by dgriswo**
Board Name: TinyS2 - ESP32-S2 Development Board
Store URL: https://www.adafruit.com/product/5029

### CODE REVIEW

**Comment by brentru** [comment]
@dgriswo  I'll add platform support in the next WipperSnapper library release (beta 12) for this, opened an issue for your tracking here https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/162

**Comment by dgriswo** [comment]
I saw your PR for the FeatherS2 and figured I could do the pin mapping for the TinyS2. I also have the FeatherS2 Neo that I can submit a PR for and test. Should I wait on the second PR until platform support is ironed out?

**Comment by brentru** [comment]
@dgriswo We'll take another PR and then queue them up. Does the FeatherS2 Neo have arduino support?

**Comment by dgriswo** [comment]
> @dgriswo Does the FeatherS2 Neo have arduino support?

Yup, just made it in 2.0.0. https://github.com/espressif/arduino-esp32/pull/5615

**Pull request merged**
