### PR TITLE
UART Pin Specification Proposal

### PR DESCRIPTION
**Pull request by lorennorman**
Making a public mess so we can talk about it

### CODE REVIEW

**Comment by lorennorman** [comment]
@brentru take a look at my diff on this one, total made up pins on the Funhouse but something to talk over

Hardware Pins:
- enforce no other options can be set for those pins in the JSON
- rx and tx would enforce either BOTH or NEITHER appear
- wouldn't appear in normal "list of pins" places on the web interface, unselectable
- would appear read-only in the "new component" pop-over if the user selects a UART component to add

Software Pins:
- can appear alongside other pin options
- rx and tx would enforce either BOTH or NEITHER appear
- these are otherwise-normal pins
- would appear read-only in the "new component" pop-over if the user selects a UART component to add

Both:
- enforce mutual exclusivity with the other (hardware OR software, not both)
- notice they've already been used if user tries to add a second UART component, advise the user

Notes:
- the JSON properties are a bit long, still thinking on that

Questions:
- are they analog or digital pins?
- your protobuf [shows an int for pin identification](https://github.com/adafruit/Wippersnapper_Protobuf/pull/129/files#r1303544019), that should be string, right?
- what `dataType` should they be?
- what am i missing?

**Comment by lorennorman** [comment]
Converted to a draft so we aren't tempted to merge

**Comment by brentru** [comment]
@lorennorman  Answering questions
- are they analog or digital pins?
  - Digital
- your protobuf [shows an int for pin identification](https://github.com/adafruit/Wippersnapper_Protobuf/pull/129/files#r1303544019), that should be string, right?
  -   Yes, this is fixed in the latest commit 
- what dataType should they be?
  - Shouldn't have one, similar to `i2cPorts` identifiers
- what am i missing?
  - We shouldn't present the option to do hardware or software, this will be determined in the UART class at compile-time . This is based on the existence and inclusion of either a hardwareserial or softwareserial class. Instead, the funhouse definition should only expose the UART hardware pins, x1 and x2.
  - Given the notes above, would it make more sense to slot this into a `uartPins` array rather than `digitalPins`, similar to how we defined `i2cPorts` ?

**Comment by lorennorman** [comment]
@brentru trying to `uartPins` dedicated property, might look like this...

hardware:
```json
      "uartPins": {
         "tx": "H1",
         "rx": "H2",
         "hardware": true
       }
```

software:
```json
      "uartPins": {
         "tx": "S1",
         "rx": "S2"
      }
```

Hardware would verify that the named pins do not exist in the digital collection, software would verify that they do exist.

Much simpler, I like this much more so far. Thoughts?

**Comment by brentru** [comment]
@lorennorman  you marked this ready for review, do you want me to fully review it?

**Pull request merged**
