### PR TITLE
Add definition for BOOT button

### PR DESCRIPTION
**Pull request by ctgreybeard**
Added the BOOT button definition. Please review to be sure I did it correctly. The instructions are out of date and I am not sure how to test with the new py-based system. Nor the old one either for that matter.

### CODE REVIEW

**Comment by brentru** [comment]
@ctgreybeard  Hi - we're working to improve the user-contribution side of WipperSnapper. 

Which instructions did you follow. Which are "out of date"? What Py based system?

**Review by brentru — APPROVED** [review]
LGTM, merging in

**Comment by brentru** [comment]
@ctgreybeard  This should now be live on IO for your use.

**Comment by ctgreybeard** [comment]
My mistake on the "out-of-date" and "py" ..., Brent. Newbee error! 🥸

**Pull request merged**
